### ISSUE TITLE
Login does not work when using Amazon login for eero, is there a way around this?

### ISSUE THREAD

**Issue by krishnadasmallya** [acaranta/docker-eero-prometheus-exporter#1]
Login does not work when using Amazon login for eero, is there a way around this?

**Comment by acaranta** [comment]
To be honest I don't really know, I just made a docker image around the existing code for eero exporter ( https://github.com/brmurphy/eero-exporter ), best I can do is what I just did : force a rebuild of the image to pull latest exporter version 😅

**Comment by krishnadasmallya** [comment]
No problem. Was just trying my luck to see if someone already have figured it out. Decompiled the android app but couldn't see API similar to the login one when I quickly skimmed through the code. So I guess, its not worth it as Amazon might change it anytime and would be hard to maintain.
