### ISSUE TITLE
Associated dashboard has some typos

### ISSUE THREAD

**Issue by brmurphy** [acaranta/docker-eero-prometheus-exporter#2]
I was reviewing and updating the exporter, and realised the associated Grafana Dashboard has some typos.

https://grafana.com/grafana/dashboards/13558-eero-wifi-networks-stats/

weury -> query

I'm happy to edit as a contributor, or just send them your way. :)

**Comment by acaranta** [comment]
ah thx a lot ... I just corrected the typo :)
